services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb:v0.1
    container_name: mariadb
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - my-net
    volumes:
      - /home/ahanaf/data/database:/var/lib/mysql
  wordpress:
    build: requirements/wordpress/.
    image: wordpress:v0.1
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
      - redis
    networks:
      - my-net 
    volumes:
      - /home/ahanaf/data/www:/var/www/html
    environment:
      URL: ${URL}
      TITLE: ${TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_ROLE: ${WP_ROLE}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST_PORT: ${DB_HOST_PORT}
      DB_HOST: ${DB_HOST}
      REDIS_HOST: redis
      REDIS_PORT: 6379
  nginx:
    build:
      context: requirements/nginx
      args:
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    image: nginx:v0.1
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    networks:
      - my-net
    volumes:
      - /home/ahanaf/data/www:/var/www/html
    ports:
      - "443:443"
  website:
    build: requirements/bonus/website/.
    image: website:v0.1
    container_name: website
    restart: always
    networks:
      - my-net
    ports:
      - "3000:3000"
  adminer:
    build: requirements/bonus/adminer/.
    image: adminer:v0.1
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - my-net

  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:v0.1
    container_name: redis
    restart: always
    networks:
      - my-net
    ports:
      - "6379:6379"
    volumes:
      - /home/ahanaf/data/redis:/data

  ftp:
    build: requirements/bonus/ftp/.
    image: ftp:v0.1
    container_name: ftp
    restart: always
    volumes:
      - /home/ahanaf/data/www:/home/ftpuser/wordpress
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppassword
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - my-net

  cadvisor:
    build: requirements/bonus/cadvisor/.
    image: cadvisor:v0.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8084:8084"
    networks:
      - my-net
    restart: on-failure

networks:
  my-net:
    driver: bridge
