services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb:v0.1
    container_name: mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - my-net
    volumes:
      - /home/ahanaf/data/database:/var/lib/mysql
  wordpress:
    build: requirements/wordpress/.
    image: wordpress:v0.1
    container_name: wordpress
    networks:
      - my-net 
    volumes:
      - /home/ahanaf/data/www:/var/www/html
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST_PORT: mariadb:3306
  nginx:
    build: requirements/nginx/.
    image: nginx:v0.1
    container_name: nginx
    networks:
      - my-net
    volumes:
      - /home/ahanaf/data/www:/var/www/html
    ports:
      - "443:443"   

networks:
  my-net:
    driver: bridge
